// <auto-generated />
using LePortail.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LePortail.Migrations
{
    [DbContext(typeof(PortailDB))]
    partial class PortailDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LePortail.Models.Candidat", b =>
                {
                    b.Property<int>("IdCandidat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCandidat"));

                    b.Property<string>("AnneesExperience")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("CheminDuCv")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DernierEmployeur")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NiveauDetude")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<short>("Tel")
                        .HasColumnType("smallint");

                    b.HasKey("IdCandidat");

                    b.ToTable("Candidat", "EspaceCandidat");
                });
#pragma warning restore 612, 618
        }
    }
}
